### ISSUE TITLE
TypeError: Plugin is not a function

### ISSUE THREAD

**Issue by jedmao** [danmartinez101/babel-preset-react-hmre#10]
Using the following configuration in my `.babelrc` file:

```json
{
  "presets": ["es2015", "react"],
  "env": {
    "development": {
      "presets": ["react-hmre"]
    }
  }
}
```

I'm getting the following error:
```
Z:\project\node_modules\babel-preset-react-hmre\node_modules\babel-plugin-react-transform\lib\index.js:258
  return new Plugin('babel-plugin-react-transform', {
         ^

TypeError: Plugin is not a function
    at exports.default (Z:\project\node_modules\babel-preset-react-hmre\node_modules\babel-plugin-react-transform\lib\index.js:258:10)
    at Function.memoisePluginContainer (Z:\project\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:127:13)
    at Function.normalisePlugin (Z:\project\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:161:32)
    at Z:\project\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:197:30
    at Array.map (native)
    at Function.normalisePlugins (Z:\project\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:173:20)
    at OptionManager.mergeOptions (Z:\project\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:271:36)
    at OptionManager.mergePresets (Z:\project\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:325:16)
    at OptionManager.mergeOptions (Z:\project\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:287:12)
    at OptionManager.mergeOptions (Z:\project\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:303:10)
```
Does this mean that `Plugin` was somehow supposed to be provided to `babel-plugin-react-transform` or is the issue, in fact, with `babel-plugin-react-transform` itself?

Any ideas?

Related issue: https://github.com/danmartinez101/babel-preset-react-hmre/issues/2

**Comment by jedmao** [comment]
[This issue](https://github.com/gaearon/babel-plugin-react-transform/issues/51) suggests it's because you're using an older version of `babel-plugin-react-transform`, but that [does not appear to be the case](https://github.com/danmartinez101/babel-preset-react-hmre/blob/b8f02f53aad75e9ebe5df0434d9b5d0729e67bc7/package.json#L19).

**Comment by jedmao** [comment]
False alarm. Somehow, I got a stale version of this module installed.
