### ISSUE TITLE
Does not work on Windows 

### ISSUE THREAD

**Issue by eriknyk** [danmartinez101/babel-preset-react-hmre#32]
By some weird reason it does not works on windows,
on OSX and Linux it works great, but it fails on windows, did you tried on windows?

```
ERROR in ./client.js                                                                                     
Module parse failed: C:\Users\erik\Projects\testprj\client.js Unexpected token (26:1)            
You may need an appropriate loader to handle this file type.                                              SyntaxError: Unexpected token (26:1)                                                                          
at Parser.pp.raise (C:\Users\erik\Projects\testprj\node_modules\acorn\dist\acorn.js:920:13)      
at Parser.pp.unexpected (C:\Users\erik\Projects\testprj\node_modules\acorn\dist\acorn.js:1483:8)                                                                                                           at Parser.pp.parseExprAtom 
(C:\Users\erik\Projects\testprj\node_modules\acorn\dist\acorn.js:330:12)                                                                                                        at Parser.pp.parseExprSubscripts (C:\Users\erik\Projects\testprj\node_modules\acorn\dist\acorn.js:225:19) 
 at Parser.pp.parseMaybeUnary (C:\Users\erik\Projects\testprj\node_modules\acorn\dist\acorn.js:204:17)                                                                                                      
at Parser.pp.parseExprOps (C:\Users\erik\Projects\testprj\node_modules\acorn\dist\acorn.js:151:19)                                                                                                         
at Parser.pp.parseMaybeConditional (C:\Users\erik\Projects\testprj\node_modules\acorn\dist\acorn.js:133:19)                                                                                                
at Parser.pp.parseMaybeAssign (C:\Users\erik\Projects\testprj\node_modules\acorn\dist\acorn.js:110:19)                                                                                                     
at Parser.pp.parseExprList (C:\Users\erik\Projects\testprj\node_modules\acorn\dist\acorn.js:657:23)                                                                                                        
at Parser.pp.parseSubscripts (C:\Users\erik\Projects\testprj\node_modules\acorn\dist\acorn.js:249:29)                                                                                                   @ multi main                 
```

my configuration:

```javascript
var path = require('path')
var webpack = require('webpack')

module.exports = {
  devtool: 'cheap-module-eval-source-map',
  entry: [
    'webpack-hot-middleware/client',
    './client.js'
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/bundle/'
  },
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development')
    })
  ],
  module: {
    loaders: [
      {
        test: /\.json$/,
        loader: 'json'
      }, {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/,
        include: path.join(__dirname, '/../'),
        query: {
          presets: [ 'react-hmre' ],
          plugins: [
            'babel-plugin-transform-decorators-legacy'
          ]
        }
      }
    ]
  }
}

```

this exactly configuration works well on OSX and Linux

Regards.

**Comment by danmartinez101** [comment]
Sorry it isn't working for you :( 

I haven't tried it on windows at all. I will get a virtual machine set up with windows so that I can figure out what is going wrong. I'll have some time this coming week to work on this problem.

What version of windows do you have?

**Comment by eriknyk** [comment]
Thank you so much, I have Windows 10 Pro

**Comment by jazznov** [comment]
I'm having this issue as well on Win 7 with Node 6.2.1, and the only workaround I've found for now seems to be to use Node 4 LTS or 5 instead. The issue seems to stem from some combination of using JSX, Webpack, Babel, Acorn JS, Node 6.x, and Windows.

A couple related related posts I've come across:
[https://github.com/danmartinez101/babel-preset-react-hmre/issues/32](https://github.com/danmartinez101/babel-preset-react-hmre/issues/32)

[https://github.com/coryhouse/pluralsight-redux-starter/issues/2](https://github.com/coryhouse/pluralsight-redux-starter/issues/2)

**Comment by OnlyRefat** [comment]
have anyone faced the issue described on stackoverflow

http://stackoverflow.com/questions/38669804/you-may-need-an-appropriate-loader-to-load-this-file-on-windows-with-webpack-not

**Comment by creamidea** [comment]
I have met the same error message. But my reason is that I wrote the wrong module.loader.include. [Here ](https://github.com/creamidea/creamidea.github.com/issues/19)is the detail. I hope to give some valid information. :)
Key: it is a good idea to use path.solve to concat the string of path, not +

**Comment by danmartinez101** [comment]
Please see https://github.com/danmartinez101/babel-preset-react-hmre/issues/46#issuecomment-250945091

Basically, happy for a PR and to help you get your fixes published.

**Comment by uismithing** [comment]
Seems I'm having the same issue - node/babel/react/webpack/windows10. Component compiles fine with npm start when it's not in the node_modules directory. After publishing with npm publish and npm install --s, the error occurs as above: You may need an appropriate loader..., unexpected token (730:3) -- which is the first character of the jsx return value in the render() method of the component. I've gone through several posts (and several hours) following all of the recommendations regarding package.json, .babelrc, webpack.config.js, the presets, text, loader, etc.. The problem still persists. Really need this to work. Very appreciative for any ideas...thanks in advance. Will continue trials...
